version: '3.3'
services:
    caddy:
        image: caddy:latest
        ports:
            - 8080:80
            - 443:443
            - 443:443/udp
        volumes:
            - ./docker/Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
            - ./docker/certs:/certs
    db:
        image: mysql:8.4
        restart: always
        environment:
            MYSQL_DATABASE: 'posts'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
    laravel:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        extra_hosts:
            - host.docker.internal:host-gateway
            - app.laravel.local:host-gateway
        ports:
            - '${APP_PORT}:80'
            - '${VITE_APP_PORT}:5173'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - db
            - caddy
volumes:
    mysql_data:
    caddy_data:
    caddy_config:
